version: '3'
services:
  mysql:
   image: mysql:5.7.8
   ports:
    - "3306:3306"
   networks:
    - petclinic
   environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
   volumes:
    - "./conf.d:/etc/mysql/conf.d:rw"
  spring:
    image: apetrovya/spring-petclinic:1.2.2
    ports:
     - "8080:8080"
    networks:
     - petclinic
    depends_on:
     - mysql
networks:
  petclinic:
    